version: '2'
services:
    cawnapp-app:
        image: cawnapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://cawnapp-postgresql:5432/cawnapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=cawnapp-elasticsearch:9300
        ports:
            - 8080:8080
    cawnapp-postgresql:
        extends:
            file: postgresql.yml
            service: cawnapp-postgresql
    cawnapp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: cawnapp-elasticsearch
